# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module DeviseTokenAuth::RegistrationsController; end
module StudyStartNotifyJob::U; end
